base_url = "https://specialists-fi.github.io"
theme = "neoathame"

compile_sass = true
build_search_index = true

[markdown]
highlight_code = false

[extra.social]
name = "specialists-fi"
avatar = "assets/tof.webp"
shortbio = "Terve! Come a tad later!"


[extra.social.links.1]
service = "github"
username = "@specialists-fi"
url = "https://github.com/specialists-fi"

[extra.social.links.2]
service = "twitter"
username = "@finnspecialist"
url = "https://twitter.com/finnspecialist"

[extra.social.links.3]
service = "telegram"
username = "techcitizens"
url = "https://t.me/techcitizens"

[extra.social.links.4]
service = "linkedin"
username = "..."
url = "https://www.linkedin.com/groups/9378498/"
